### ISSUE TITLE
Missing Composer Install  for Trellis new site.com cmd

### ISSUE THREAD

**Issue by HXavS** [roots/trellis-cli#160] opened 2021-03-11 05:50 UTC
I am very new to using Trellis so I could be wrong.  I set up Trellis earlier today on a fresh install of Ubuntu 20.04 LTS. 

When I ran `Trellis New` and and following the documentation and got to `Trellis UP` I ended up stuck for a bit after some troubleshooting. (Homebrew bash references need to go into .bashrc not .profile in ubuntu 20.04 LTS ).  The VM had started but nothing was working.

The `Trellis New` cmd doesn't create on the all packages necessary. I had to use` Composer create-project roots/bedrock site` to have all the necessary file. And it worked fine after that. 

The cause looks the be  [line 114 in the new cmd](https://github.com/roots/trellis-cli/blob/57bb8cefcf1c020a6a1482a5dacbcce523137a01/cmd/new.go). It appears the CLI is only downloading and saving the files direct with an http client rather then using Composer. `Composer Create-project` triggers `Composer install` when run. 

I was not seeing any composer install exec between new and up cmds to get the remains files. 

Let me know what I a missing if I am wrong thanks. 
- J

**Comment by HXavS** [comment] 2021-03-11 21:46
Did what I thought should fix the issue. Not familiar with go. 
Please advice, Should I do a pull request

[Updated New Command](https://github.com/HXavS/trellis-cli/blob/master/cmd/new.go)

**Comment by swalkinshaw** [comment] 2021-03-12 03:55
> The Trellis New cmd doesn't create on the all packages necessary. 

You said "packages" were missing, and by looking at your commits, it looks like you mean that `composer install` wasn't run? That's correct and by design. Composer packages aren't needed locally so they aren't installed. 

Composer packages get installed on the server during the Ansible provisioning process in development (see [here](https://github.com/roots/trellis/blob/efe33fb7c7b7a227873ae35751b790d2cc357eb0/roles/wordpress-install/tasks/main.yml#L24-L30)), or during the *deploy* process for remote (staging/production) servers (see [here](https://github.com/roots/trellis/blob/efe33fb7c7b7a227873ae35751b790d2cc357eb0/roles/deploy/hooks/build-after.yml#L28-L32)).

Did you run into any issues or just figured something was missing? I agree it's a bit confusing because normally you'd expect to have the composer packages installed locally.

**Comment by HXavS** [comment] 2021-03-13 21:54
Oh okay that makes sense. 

I will retry with a new deployment. 
I had issues running trellis up. It started the VM but a lot was not installed. I was able to trellis ssh development but PHP was not installed. After running composer install on the project with the VM off trellis up was working. I was using Ubuntu 20.04 LTS in hyper-v with nested virtualization.

**Comment by swalkinshaw** [comment] 2021-03-15 21:58
That's definitely unexpected, but hard to say without any Ansible output logs.

Closing this issue since it was related to composer, but feel to open a more specific one if you find any errors or it happens again.

**Closed by swalkinshaw** 2021-03-15 21:58 UTC
